runtime: nodejs18

env_variables:
  FIREBASE_API_KEY: "AIzaSyDUBmzr8sXEFF6_gzEIjTeoJWSOymYqUOc"
  FIREBASE_AUTH_DOMAIN: "kostify-database.firebaseapp.com"
  FIREBASE_PROJECT_ID: "kostify-database"
  FIREBASE_STORAGE_BUCKET: "kostify-database.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "176060989098"
  FIREBASE_APP_ID: "1:176060989098:web:6216bd2769e43010c89ad3"
  GOOGLE_APPLICATION_CREDENTIALS: "src/config/serviceAccountKey.json"

handlers:
  - url: /.*
    script: auto